### ISSUE TITLE
Mobile Touch Support

### ISSUE THREAD

**Issue by manuelprojects** [maoosi/jquery.timeliny#1]
Does will be supported mobile touch? At the moment seems not working tring swiping the timeline.

**Comment by maoosi** [comment]
Hi @manuelprojects, I invite you to go to the following url with the concerned touch device:  http://www.whatsmybrowser.org

Please send me the generated link, so I will be able to see what's your exact config. If I can replicate the problem, I should be able to fix it for the next release.

**Comment by manuelprojects** [comment]
Hi @maoosi i've implemented the mobile support using Hammerjs directly in the app core.

Please check if this can be done in your release.

`var mc = new Hammer(el);
            mc.get('pan').set({ direction: Hammer.DIRECTION_HORIZONTAL });

```
        mc.on("panmove", function(ev) {
            selected.style.left =  (ev.deltaX) - x_elem  + 'px';
        });

        mc.on("panstart", function(ev) {
            _drag_init($el.find('.'+ options.className +'-timeline')[0]);
        });

        mc.on("panend", function(ev) {
            _stop_move();
        });`
```

**Comment by maoosi** [comment]
Thanks @manuelprojects, this is indeed a good solution for a one-shot project. 

However, I don't want to include a third party library like Hammer.js within the core of the plugin. I'll try to implement it in pure JavaScript for the next release.

Can you please let me know with which device it was not working before your Hammer.js implementation?

**Comment by manuelprojects** [comment]
Hi,
Abut the mobile support with this implemention the timeline became scrollable with touch events and think that it s really an important feature that right now its only working with mouse movment
