### ISSUE TITLE
Hide blank years.

### ISSUE THREAD

**Issue by joshuaiz** [maoosi/jquery.timeliny#2]
Hello, great plugin.

I'd like to only show divs/years that have a data-year attribute. Is that possible or can that be added?

For example, I have a timeline with a lot of milestones over the last hundred years however there are many years without anything. I don't want to show those years, only those with content.

Thanks!

**Comment by maoosi** [comment]
Hi @joshuaiz, I'll have a look at it when I'll get some time ;)

**Comment by maoosi** [comment]
@joshuaiz I've just released the version 1.0.1 that includes an option:

```javascript
$('#demo').timeliny({
    hideBlankYears: true
});
```
